
# 询问未引入知识库的内容，会不断触发重写，重写Request条件边有效
GET http://127.0.0.1:8080/ai/rag/graph/call?message=如何在Spring Ai Alibaba中添加子图


###
# 询问知识库内容，可以正常检索并输出
GET http://127.0.0.1:8080/ai/rag/graph/call?message=spring ai alibaba的环境要求


###
# 常规对话，不会进入知识库相关检索链路
GET http://127.0.0.1:8080/ai/rag/graph/call?message=你好